### ISSUE TITLE
[Question] Available metrics

### ISSUE THREAD

**Issue by Voronenko** [KuguHome/openhab-prometheus-metrics#2]
Should there be possible to extract values of the thing's  items?

I.e. saying I have thing, exporting numeric values as 3-5 items (like temperature, humudity, etc)
should there be possible to scrape those values into prometheus ?

Can you provide some initial guidance?

**Comment by pokerazor** [comment]
Hi. No, the prometheus metrics bundle is not about exporting the operational values of openHAB's Channels/Items, but to look "behind the scenes" at some internal systematic metrices for maintenance, operation, debugging etc.

If you want to get the Item's values, you should use the general HTTP REST interface dedicated for that purpose, e.g. like
http://localhost:8080/rest/items?fields=state

Does this help you or are there additional questions?

**Comment by Voronenko** [comment]
Thanks for prompt response. More or less helps. I was aware on that API, but was hoping to get prometheus syntax out of the box

**Comment by pokerazor** [comment]
During implementation, we thought about the use case you seem to evaluate but didn't deem it very valuable. If you think it may be actually valuable, it should be fairly straightforward to implement as an additional `Exposable` component, maybe see here as a starting point: https://github.com/KuguHome/openhab-prometheus-metrics/blob/master/com.kuguhome.openhab.prometheusmetrics/src/main/java/com/kuguhome/openhab/prometheusmetrics/exposable/OpenHABThingStateMetric.java

We would consider merging a pull request on this, if you implement it.

**Comment by pokerazor** [comment]
Personally, I think, using Prometheus as a kind of "persistence" layer is more of a hack. openHAB has good support for Time Series Databases like InfluxDB as a persistence module. The data can be displayed on Grafana as a different datasource, exactly in the same way as Prometheus is.

**Comment by Voronenko** [comment]
I am about to use it more as an alerting system. I am already using it as a monitoring solution on a work projects, together with grafana & alert manager - and thus can create quite sophisticated alerting scenarios, compared to only storing data to some relational or time-series db.
